"""Compile a fitted DecisionTreeClassifier into an integer-only C header.

    python export_tree.py --model model.pkl --out ../firmware/nano/model.h

Thresholds round to uint32 so the output has no floats - the ATmega328P has no
FPU and one float compare drags in soft-float.
"""
from __future__ import annotations

import argparse
import pickle
from pathlib import Path

import numpy as np

from features import FEATURE_NAMES

HEADER = """// GENERATED by pipeline/export_tree.py -- do not edit by hand.
//
// source model : {model}
// depth        : {depth}
// nodes        : {nodes}
//
// Integer-only: every threshold is a squared magnitude in raw MPU6050 counts,
// so this compiles without soft-float support on AVR.
#pragma once
#include <Arduino.h>

#define MODEL_N_FEATURES {n_features}

// Feature indices (see detect.h):
{feature_key}

// Returns 1 for fall, 0 for normal activity.
static uint8_t modelPredict(const uint32_t* f) {{
"""

FOOTER = """}
"""


def emit(tree, node: int, depth: int, lines: list[str]) -> None:
    pad = "  " * (depth + 1)
    t = tree.tree_
    if t.children_left[node] == -1:
        cls = int(np.argmax(t.value[node][0]))
        lines.append(f"{pad}return {cls};  // n={int(t.n_node_samples[node])}")
        return
    feat = int(t.feature[node])
    thresh = int(round(float(t.threshold[node])))
    if thresh < 0:
        thresh = 0
    lines.append(f"{pad}if (f[{feat}] <= {thresh}UL) {{  // {FEATURE_NAMES[feat]}")
    emit(tree, int(t.children_left[node]), depth + 1, lines)
    lines.append(f"{pad}}} else {{")
    emit(tree, int(t.children_right[node]), depth + 1, lines)
    lines.append(f"{pad}}}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", type=Path, default=Path("model.pkl"))
    ap.add_argument("--out", type=Path, default=Path("../firmware/nano/model.h"))
    args = ap.parse_args()

    with args.model.open("rb") as fh:
        clf = pickle.load(fh)

    n_features = int(clf.n_features_in_)
    if n_features != len(FEATURE_NAMES):
        raise SystemExit(
            f"model expects {n_features} features, features.py defines "
            f"{len(FEATURE_NAMES)} -- exporting this would misalign them")

    feature_key = "\n".join(f"//   [{i}] {n}" for i, n in enumerate(FEATURE_NAMES))

    lines: list[str] = []
    emit(clf, 0, 0, lines)

    text = (HEADER.format(model=args.model.name,
                          depth=int(clf.get_depth()),
                          nodes=int(clf.tree_.node_count),
                          n_features=n_features,
                          feature_key=feature_key)
            + "\n".join(lines) + "\n" + FOOTER)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out}  ({text.count(chr(10))} lines, "
          f"depth {clf.get_depth()}, {clf.tree_.node_count} nodes)")


if __name__ == "__main__":
    main()
